object Versions {
    const val core = "_"
    const val gradlePlugin = "_"
    const val kotlin = "_"
    const val timber = "_"
    const val appCompat = "_"
    const val material = "_"
    const val constraintLayout = "_"
    const val jUnit = "_"
    const val junitExt = "_"
    const val espresso = "_"
    const val compose = "_"
    const val lifecycleRuntime = "_"
    const val composeActivity = "_"
    const val coil = "_"
}