import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {
    const val activity_compose: String = "androidx.activity:activity-compose:_"

    const val appcompat: String = "androidx.appcompat:appcompat:_"

    const val androidx_compose_compiler_compiler: String = "androidx.compose.compiler:compiler:_"

    const val androidx_compose_material_material: String = "androidx.compose.material:material:_"

    const val ui: String = "androidx.compose.ui:ui:_"

    const val ui_test_junit4: String = "androidx.compose.ui:ui-test-junit4:_"

    const val ui_tooling: String = "androidx.compose.ui:ui-tooling:_"

    const val ui_tooling_preview: String = "androidx.compose.ui:ui-tooling-preview:_"

    const val core_ktx: String = "androidx.core:core-ktx:_"

    const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:_"

    const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:_"

    const val com_google_android_material_material: String =
            "com.google.android.material:material:_"

    const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    const val coil: String = "io.coil-kt:coil:_"

    const val junit_junit: String = "junit:junit:_"

    const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"
}
